apiVersion: v1
kind: ConfigMap
metadata:
  name: env-contentmanager
  labels:
    app: eulen-tomcat-dev
data:
  db_url: jdbc:as400://eulenpre.eulen.com;naming=system;errors=full;metadata source=0;"
  APP_WAR_NAME: contentmanager.war
  APP_CONTEXT_PATH: contentmanager
  ldap_urls: ldap://eulen.ms:389/
  webservices_path: https://preaks.eulen.com/eulen-rest/version
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-env-contentmanager
type: Opaque
stringData:
  db_password: $db_p
  db_username: $db_u
  ldap_username: $ldap_u
  ldap_password: $ldap_p
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contentmanager-deployment
  labels:
    app: eulen-tomcat-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eulen-tomcat-dev
  template:
    metadata:
      labels:
        app: eulen-tomcat-dev
    spec:
      containers:
        - name: tomcat-contentmanager
          image: eulen-tomcat-contentmanager
          imagePullPolicy: IfNotPresent
          env:
            - name: db_password
              valueFrom: 
                secretKeyRef:
                  name: secret-env-contentmanager
                  key: db_password
            - name: db_username
              valueFrom: 
                secretKeyRef:
                  name: secret-env-contentmanager
                  key: db_username
            - name: db_url
              valueFrom: 
                configMapKeyRef:
                  name: env-contentmanager
                  key: db_url
            - name: APP_WAR_NAME
              valueFrom: 
                configMapKeyRef:
                  name: env-contentmanager
                  key: APP_WAR_NAME
            - name: APP_CONTEXT_PATH
              valueFrom: 
                configMapKeyRef:
                  name: env-contentmanager
                  key: APP_CONTEXT_PATH
            - name: ldap_urls
              valueFrom: 
                configMapKeyRef:
                  name: env-contentmanager
                  key: ldap_urls
            - name: ldap_username
              valueFrom: 
                secretKeyRef:
                  name: secret-env-contentmanager
                  key: ldap_username
            - name: ldap_password
              valueFrom: 
                secretKeyRef:
                  name: secret-env-contentmanager
                  key: ldap_password
            - name: webservices_path
              valueFrom: 
                configMapKeyRef:
                  name: env-contentmanager
                  key: webservices_path
---
apiVersion: v1
kind: Service
metadata:
  name: contentmanager-service
  labels:
    app: eulen-tomcat-dev
spec:
  type: NodePort
  selector:
    app: eulen-tomcat-dev
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080