#FROM tomcat:9.0
#FROM registry.eulen.com/eulen-tomcat:9-jre11-b31 
FROM registry.eulen.com/eulen-tomcat:9-jre11-b28
COPY Api_Rest_Equipo1.war /usr/local/tomcat/webapps/Api_Rest_Equipo1.war
COPY decidim_equipo1.db /home/decidim_equipo1.db
EXPOSE 8080
#CMD ["catalina.sh", "run"]
