apiVersion: v1
kind: ConfigMap
metadata:
  name: env-contentmanager
  labels:
    app: eulen-tomcat-dev
data:
  DB_URL: jdbc:as400://eulenpre.eulen.com;naming=system;errors=full;metadata source=0;"
  DB_DRIVER: com.ibm.as400.access.AS400JDBCDriver
  ldap_urls: ldap://eulen.ms:389/
  webservices_path: https://preaks.eulen.com/eulen-rest/version
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-env-contentmanager
type: Opaque
stringData:
  DB_PASSWORD: init0224
  DB_USER: CONTENTMAN
  ldap_username: adminCManager
  ldap_password: Temporal.00
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contentmanager-deployment
  labels:
    app: eulen-tomcat-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eulen-tomcat-dev
  template:
    metadata:
      labels:
        app: eulen-tomcat-dev
    spec:
      containers:
        - name: tomcat-contentmanager
          image: eulen-tomcat-contentmanager
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: secret-env-contentmanager
                  key: DB_PASSWORD
            - name: DB_USER
              valueFrom: 
                secretKeyRef:
                  name: secret-env-contentmanager
                  key: DB_USER
            - name: DB_URL
              valueFrom: 
                configMapKeyRef:
                  name: env-contentmanager
                  key: DB_URL
            - name: DB_DRIVER
              valueFrom: 
                configMapKeyRef:
                  name: env-contentmanager
                  key: DB_DRIVER
            - name: ldap_urls
              valueFrom: 
                configMapKeyRef:
                  name: env-contentmanager
                  key: ldap_urls
            - name: ldap_username
              valueFrom: 
                secretKeyRef:
                  name: secret-env-contentmanager
                  key: ldap_username
            - name: ldap_password
              valueFrom: 
                secretKeyRef:
                  name: secret-env-contentmanager
                  key: ldap_password
            - name: webservices_path
              valueFrom: 
                configMapKeyRef:
                  name: env-contentmanager
                  key: webservices_path
---
apiVersion: v1
kind: Service
metadata:
  name: contentmanager-service
  labels:
    app: eulen-tomcat-dev
spec:
  type: NodePort
  selector:
    app: eulen-tomcat-dev
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080